### ISSUE TITLE
Commit issue

### ISSUE THREAD

**Issue by hakichris** [Yemisirach/Awsome-book-ES6#2]
PLEASE DO NOT COMMIT EXTRA CODE AFTER YOU SUBMIT YOUR PROJECT FOR REVIEW, THIS MAKES REVIEWING YOUR CODE MORE DIFFICULT.

**Comment by Yemisirach** [comment]
PLEASE DO NOT COMMIT EXTRA CODE AFTER YOU SUBMIT YOUR PROJECT FOR REVIEW, THIS MAKES REVIEWING YOUR CODE MORE DIFFICULT.

Thank you for you suggestion I will do.
